### ISSUE TITLE
Consider adding an RSS feed to https://css.oddbird.net/

### ISSUE THREAD

**Issue by tomayac** [oddbird/css-sandbox#11]
I would like to subscribe to your site :-)

**Comment by mirisuzanne** [comment]
I treat this site more like a sandbox than a blog, so I'm most often pushing minor updates - adding/removing links, and moving things around. It's very rare that I add new pages. I'm not sure the best way to organize an RSS feed around that sort of content. Or would you just want updates when a new page is added? Even then, new pages are often posted with just a few notes, and TODO items, without much real content -- and then they get fleshed out over time.

**Comment by tomayac** [comment]
I see, thanks for the explanation. I guess getting a ping once a new item is added would still be valuable, and be it just for knowing that a new interesting discussion is happening or ongoing. If you add a feed, I'd happily subscribe, but I might well be the only subscriber, so obviously this is very low priority.

**Comment by mirisuzanne** [comment]
Here you go! 

https://css.oddbird.net/feed.xml

Currently it posts pages whenever I add to their changelog.

Another approach might be having all the posts once, but change the date & title to latest changelog? I don't know. Feel free to file a new issue (or comment again here) if this approach doesn't work.

**Comment by tomayac** [comment]
Since there's no notification for GitHub emoji reactions, here's an explicit comment emoji reaction: ❤️! Thanks so much for adding the feed! Really appreciated!

**Comment by mirisuzanne** [comment]
Great!

I made it so that new pages are added to the feed as they are created (so now all the pages should show up).
